'use strict';
const {csvCell,html}=require('./core');
const cell=v=>typeof v==='number'&&Number.isFinite(v)?String(v):csvCell(v);
const columns=['section','kind','snapshot_date','captured_at','appointment_date','weekday','city','state','industry','history_source','confirmed_cards','inferred_only_cards','total_cards','two_day_total','average_cards','sample_days','scheduled_days','reconstructed_days','historical_average','historical_sample_days','scheduled_sample_days','reconstructed_sample_days','difference_from_average','percent_vs_average','previous_weekday_date','previous_weekday_cards','previous_weekday_source','difference_from_previous','percent_vs_previous','baseline_from','baseline_through','comparison_note','note'];
function csv(data){
 const rows=[...data.rows.map(r=>({section:data.filters.kind==='forward'?'future_comparison':'history_detail',...r})),...data.weekdaySummary.map(r=>({section:'weekday_profile',...r}))];
 return '\ufeff'+[columns.map(cell).join(','),...rows.map(r=>columns.map(c=>cell(r[c])).join(','))].join('\r\n');
}
function table(rows,keys){return `<table><thead><tr>${keys.map(k=>`<th>${html(k.replaceAll('_',' '))}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${keys.map(k=>`<td>${html(r[k]??'—')}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${keys.length}">No measured records for these filters.</td></tr>`}</tbody></table>`;}
function reportHTML(data){
 const f=data.filters;
 const keys=f.kind==='forward'?['appointment_date','weekday','city','state','industry','total_cards','historical_average','historical_sample_days','scheduled_sample_days','reconstructed_sample_days','difference_from_average','percent_vs_average','previous_weekday_date','previous_weekday_cards','previous_weekday_source']:['appointment_date','weekday','city','state','industry','history_source','total_cards','confirmed_cards','inferred_only_cards'];
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>NextAppt Weekday Inventory Report</title><style>body{font:13px Arial;color:#173047;margin:28px}h1{color:#087c88}table{border-collapse:collapse;width:100%;font-size:10px;margin:18px 0}th,td{padding:7px;border-bottom:1px solid #dbe7eb;text-align:left}th{background:#edf6f7}p{line-height:1.6}.note{padding:12px;background:#f0f6f8}@media print{@page{size:landscape;margin:10mm}body{margin:0}thead{display:table-header-group}tr{break-inside:avoid}}</style></head><body><h1>NextAppt • ${f.kind==='forward'?'Future supply vs weekday history':'Historical weekday inventory'}</h1><p>${html(f.from)} – ${html(f.to)} · ${html(f.city||'All cities')} · ${html(f.industry||'All industries')} · ${html(data.timezone)}<br>Weekday filter: ${html(f.weekday==='all'?'All weekdays':['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][Number(f.weekday)])} · History source: ${html(f.historySource)} · Baseline: ${html(f.historyWeeks)} weeks</p><div class="note">${html(data.caveat)}</div>${f.kind==='history'?'<h2>Monday–Sunday profile across the selected date range</h2>'+table(data.weekdaySummary,['weekday','city','state','industry','average_cards','sample_days','scheduled_days','reconstructed_days','min_cards','max_cards']):'<p>Future counts are 1 p.m. snapshots. Historical counts are later daily captures or reconstructed offers. Collection timing and coverage differ, so the difference does not establish demand. Percentages are unavailable when the baseline is missing or zero.</p>'}<h2>${f.kind==='history'?'Selected history detail':'Future date comparisons'}</h2>${table(data.rows,keys)}<p>Previous weekday means exactly seven days before the target appointment date. Missing history is unavailable, not zero. Current-day partial historical data is excluded. Averages are per market and use only matching observed weekdays; they are not summed across cities with different coverage.</p><p>Generated ${html(new Date().toISOString())} · Definition version ${data.definitionVersion} · Print → Save as PDF</p></body></html>`;
}
module.exports={csv,reportHTML};
